version: '3.8'
services:
  cinema-client:
    container_name: cinema-client
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c 'yarn && yarn dev'
  web:
    image: nginx:latest
    container_name: cinema-dev-nginx
    restart: 'on-failure'
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
